name: cardapio
description: Inovador CardApp
publish_to: none
version: 1.1.3
code: 2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_secure_storage: ^4.2.1
  flutter_staggered_grid_view: ^0.4.0
  firebase_analytics: ^8.3.1
  firebase_storage: ^10.0.3
  firebase_messaging: ^10.0.6
  image_picker: ^0.8.4
  flutter_masked_text: ^0.8.0
  intl: ^0.17.0
  auto_animated: ^3.0.0
  path_provider: ^2.0.3
  web_socket_channel: ^2.1.0
  get_it: ^7.2.0
  charts_flutter: ^0.11.0
  cpfcnpj: ^1.0.3
  shimmer: ^2.0.0
  firebase_core: ^1.6.0
  provider: ^6.0.0
  geolocator: ^7.6.0
  google_maps_flutter: ^2.0.8
  google_place: ^0.4.3
  
  stripe_payment: ^1.1.4
  mask_text_input_formatter: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_signin_button: ^2.0.0
  firebase_auth: ^3.1.0
  carousel_slider: ^4.0.0
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: CustomTable
      fonts:
        - asset: fonts/CustomIcon.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto Condensed-300.ttf
          weight: 300
        - asset: assets/fonts/Roboto Condensed-regular.ttf
        - asset: assets/fonts/Roboto Condensed-700.ttf
          weight: 700
  assets:
    - image/dining-table.svg
    - image/emoji_fome.png
    - image/emoji_triste.png
    - image/restaurant.jpg
    - image/icon.png
    - image/icon_whatsapp.png
    - image/emoji_piscada.png
    - assets/images/smiley.png
    - assets/images/my_app.png
    - assets/images/breakfast.png
    - assets/images/icon_solo.png
    - assets/images/gpay.png
    - assets/images/gpay.xml
    - assets/images/credit-card.png
    - assets/images/relaxing.png
    - assets/images/checked.png
    - assets/images/user.png
